apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  clusterIP: None  # headless, cada broker terá DNS fixo
  ports:
  - port: 9092
    name: broker
  selector:
    app: kafka
