apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092
          name: broker
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.kafka.svc.cluster.local:2181"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        command:
        - sh
        - -c
        - |
          ID=$(echo ${HOSTNAME##*-})
          export KAFKA_BROKER_ID=$((ID+1))
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$HOSTNAME.kafka.kafka.svc.cluster.local:9092
          exec /etc/confluent/docker/run
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
