apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    release: kube-prometheus-stack   # precisa bater com o Prometheus
spec:
  selector:
    matchLabels:
      app: kafka-exporter            # precisa bater com o Service
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
    - port: metrics
      interval: 30s
