apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
spec:
  ports:
    - name: metrics
      port: 9308
      targetPort: metrics
  selector:
    app: kafka-exporter
