apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        args:
          - --kafka.server=kafka-0.kafka.kafka.svc.cluster.local:9092
          - --kafka.server=kafka-1.kafka.kafka.svc.cluster.local:9092
          - --kafka.server=kafka-2.kafka.kafka.svc.cluster.local:9092
        ports:
        - name: metrics
          containerPort: 9308
