apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
    - port: metrics
      interval: 15s
