apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  namespace: kafka
  labels:
    app: zookeeper
    id: "2"
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: follower
  - port: 3888
    name: election
  selector:
    app: zookeeper
    id: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-2
  namespace: kafka
  labels:
    app: zookeeper
    id: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      id: "2"
  template:
    metadata:
      labels:
        app: zookeeper
        id: "2"
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: follower
        - containerPort: 3888
          name: election
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
