apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: kafka
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  ZOOKEEPER_SYNC_LIMIT: "2"
  ZOOKEEPER_SERVERS: "zookeeper-0.zookeeper.kafka.svc.cluster.local:2888:3888;zookeeper-1.zookeeper.kafka.svc.cluster.local:2888:3888;zookeeper-2.zookeeper.kafka.svc.cluster.local:2888:3888"
  dummy: "ignore"
