apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        image: redis:7
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-master-data
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.56.0
        ports:
        - containerPort: 9121
        args:
          - "--redis.addr=redis://localhost:6379"
      volumes:
      - name: redis-master-data
        persistentVolumeClaim:
          claimName: redis-master-pvc
