apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-pv
  namespace: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:   # 👉 em dev, grava no diretório local do nó
    path: /data/redis/master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
