apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
  selector:
    app: redis-master   # ou redis-slave, dependendo de qual deployment está o sidecar
