apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        image: redis:7
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-master-data
      volumes:
      - name: redis-master-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-master
