apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-slave2-pv
  namespace: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis/slave2   # diretório no nó
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-slave2-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
