apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  namespace: redis
  annotations:
    oci.oraclecloud.com/load-balancer-type: nlb
    oci.oraclecloud.com/subnet1: ocid1.vcn.oc1.sa-vinhedo-1.amaaaaaap3sdp6qamrlrom647ypyyergw4rbzj32uaegjlyzvdl6judrnkya
spec:
  type: LoadBalancer
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
