apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave2
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave2
  template:
    metadata:
      labels:
        app: redis-slave2
    spec:
      containers:
      - name: redis-slave2
        image: redis:7
        ports:
        - containerPort: 6379
        args: ["--slaveof", "redis-master", "6379"]
        volumeMounts:
        - mountPath: /data
          name: redis-slave2-data
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.56.0
        ports:
        - containerPort: 9121
        args:
          - "--redis.addr=redis://localhost:6379"
      volumes:
      - name: redis-slave2-data
        persistentVolumeClaim:
          claimName: redis-slave2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave2-exporter
  namespace: redis
  labels:
    app: redis-slave2-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9121
      targetPort: 9121
      protocol: TCP
      name: metrics
  selector:
    app: redis-slave2
