apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - { key: app, operator: In, values: ["redis-exporter", "redis-slave1-exporter", "redis-slave2-exporter"] }
  namespaceSelector:
    matchNames:
      - redis
  endpoints:
    - port: metrics
      interval: 15s

