apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.56.0
        args:
          - "--redis.addr=redis-master:6379"
        ports:
          - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
  selector:
    app: redis-exporter
