apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:cloud-controller-manager
rules:
- apiGroups: ['']
  resources: ['events', 'endpoints']
  verbs: ['create', 'patch', 'update']
- apiGroups: ['']
  resources: ['nodes']
  verbs: ['*']
- apiGroups: ['']
  resources: ['services', 'services/status']
  verbs: ['get', 'list', 'update', 'watch', 'patch']
- apiGroups: ['']
  resources: ['persistentvolumes']
  verbs: ['get', 'list', 'watch', 'update']
- apiGroups: ['']
  resources: ['configmaps']
  verbs: ['get', 'list', 'watch']
- apiGroups: ['coordination.k8s.io']
  resources: ['leases']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
